const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const android = path.join(root, "android-ocr-prototype");
const gradle = fs.readFileSync(path.join(android, "app", "build.gradle"), "utf8");
const moduleGradle = fs.readFileSync(path.join(android, "ocr-feature", "build.gradle"), "utf8");
const manifest = fs.readFileSync(path.join(android, "app", "src", "main", "AndroidManifest.xml"), "utf8");
const moduleManifest = fs.readFileSync(path.join(android, "ocr-feature", "src", "main", "AndroidManifest.xml"), "utf8");
const scan = fs.readFileSync(path.join(android, "ocr-feature", "src", "main", "java", "tw", "searchbefore", "ocr", "ScanActivity.java"), "utf8");
const contract = fs.readFileSync(path.join(android, "ocr-feature", "src", "main", "java", "tw", "searchbefore", "ocr", "OcrContract.java"), "utf8");
const qualityEstimator = fs.readFileSync(path.join(android, "ocr-feature", "src", "main", "java", "tw", "searchbefore", "ocr", "OcrQualityEstimator.java"), "utf8");
const webBridge = fs.readFileSync(path.join(root, "form-ocr-ui.js"), "utf8");

assert.match(gradle, /applicationId "tw\.searchbefore\.ocrprototype"/, "OCR 必須維持獨立原型 App");
assert.match(gradle, /implementation project\(":ocr-feature"\)/);
assert.match(moduleGradle, /com\.android\.library/);
assert.match(moduleGradle, /namespace "tw\.searchbefore\.ocr"/);
assert.match(moduleGradle, /play-services-mlkit-document-scanner:16\.0\.0/);
assert.match(moduleGradle, /text-recognition:16\.0\.1/);
assert.match(moduleGradle, /text-recognition-chinese:16\.0\.1/);
assert.doesNotMatch(manifest, /android\.permission\.(?:INTERNET|READ_|WRITE_)/, "原型 App 不得要求網路或廣泛檔案權限");
assert.doesNotMatch(moduleManifest, /android\.permission\.(?:INTERNET|READ_|WRITE_)/, "OCR 模組不得要求網路或廣泛檔案權限");
assert.match(moduleManifest, /android:exported="false"/, "掃描 Activity 不得供外部 App 任意啟動");
assert.match(scan, /setGalleryImportAllowed\(false\)/);
assert.match(scan, /OcrContract\.EXTRA_OCR_RESULT_JSON/);
assert.match(scan, /requestId = OcrContract\.requestIdFrom/);
assert.match(scan, /completedSuccessfully && !standaloneMode/);
assert.match(scan, /scanButton\.setText\("再掃描一張"\)/);
assert.match(scan, /\.put\("requiresReview", true\)/);
assert.match(scan, /\.put\("autoCommitAllowed", false\)/);
assert.match(scan, /ChineseTextRecognizerOptions/);
assert.match(scan, /TextRecognizerOptions\.DEFAULT_OPTIONS/, "日期與數字必須同時使用 Latin 模型交叉判斷");
assert.match(scan, /Tasks\.whenAllComplete/, "兩個裝置端模型應並行辨識");
assert.match(scan, /recognitionNumericConflict/);
assert.match(scan, /alternativeBlocks/);
assert.match(contract, /PQC_OCR_SCAN_REQUEST/);
assert.match(contract, /PQC_OCR_SCAN_RESULT/);
assert.match(contract, /PQC_OCR_WEB_READY/);
assert.match(contract, /public static Intent createScanIntent/);
assert.match(contract, /public static String resultJsonFrom/);
assert.match(scan, /for \(Text\.Line line : block\.getLines\(\)\)/);
assert.doesNotMatch(scan, /Base64|putExtra\([^\n]*Bitmap|localStorage/i, "不得回傳或保存照片內容");
assert.match(qualityEstimator, /contrastScore/);
assert.match(qualityEstimator, /inkRatio/);
assert.match(qualityEstimator, /documentCoverage/);
assert.match(qualityEstimator, /multipleDocumentsDetected/);
assert.match(qualityEstimator, /horizontalRegions > 1 && verticalRegions > 1/, "單一表格上下分區不得直接誤判成多份文件");
assert.match(webBridge, /event\.ports\s*&&\s*event\.ports\[0\]/);
assert.match(webBridge, /twaPort\.onmessage/);

console.log("Android OCR 原型：雙模型、品質量測、套件隔離與不傳照片規則通過");
