const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const sw = fs.readFileSync(path.join(root, "sw.js"), "utf8");

const inlineScripts = [];
const scriptRe = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
let match;
while ((match = scriptRe.exec(html))) inlineScripts.push(match[1]);
assert.ok(inlineScripts.length >= 2, "應找到主程式的 inline scripts");
inlineScripts.forEach((code, index) => new vm.Script(code, { filename: `index-inline-${index + 1}.js` }));

assert.ok(html.indexOf('<script src="./service-config.js"></script>') < html.indexOf("const DATA="), "service-config.js 必須在主程式前載入");
assert.ok(html.indexOf('<script src="./account.js"></script>') < html.indexOf("const DATA="), "account.js 必須在主程式前載入");
assert.ok(html.indexOf('<script src="./safety.js"></script>') < html.indexOf("const DATA="), "safety.js 必須在主程式前載入");
assert.ok(html.indexOf('<script src="./farm-records.js"></script>') < html.indexOf("const DATA="), "farm-records.js 必須在主程式前載入");
assert.match(html, /const APP_VERSION="1\.8\.0"/);
assert.match(html, /const SCHEMA_VERSION=3/);
assert.match(html, /PQC_SAFETY\.shouldShowVolumeApprox\(unit\)/);
assert.match(html, /PQC_SAFETY\.directCropLevels\(crop,DATA\)/);
assert.match(html, /id="rNotify" disabled/);
assert.match(html, /id="phiCustom" type="number" min="1" max="365"/);
assert.match(html, /function applyCustomPhi\(btn\)/);
assert.match(html, /PQC_SAFETY\.harvestStatus\(records,input\.plotId,input\.date\)/);
assert.match(html, /PQC_FARM\.buildTimeline\(list,farmList,p\.id\)/);
assert.match(html, /PQC_FARM\.exportCombinedCsv\(pesticideList,farmList/);
assert.match(html, /href="\$\{TRIAL_FORM_URL\}"[^>]*>開啟試用申請表<\/a>/);
assert.match(html, /id="homeFeatures"/);
assert.match(html, /function focusHomeSearch\(\)/);
assert.match(html, /function searchPlotCrops\(raw\)/);
assert.match(html, /function pickPlotCrop\(crop\)/);
assert.match(html, /function useCustomPlotCrop\(\)/);
assert.match(html, /data-crop="" data-custom="0" oninput="searchPlotCrops\(this\.value\)"/);
assert.match(html, /cropSource:linkedCrop\?"registered":"custom"/);
assert.match(html, /從噴藥前，一路接到採收後/);
assert.match(html, /合法用藥查詢/);
assert.match(html, /安全採收連動/);
assert.match(html, /id="accountInner" aria-live="polite"/);
assert.match(html, /付款功能尚未開放<\/button>/);
assert.match(html, /id="supportLink"[^>]*rel="noopener noreferrer"/);
assert.match(html, /贊助不會解鎖 Pro/);
assert.match(html, /parsed\.protocol==="https:"/);
assert.doesNotMatch(html, /id="shopLinkInner"/);
assert.doesNotMatch(html, /function (?:renderShopLink|saveShopLink|disconnectShop)\(/);
assert.doesNotMatch(html, /linkedShop:store\.get\("linkedShop"\)/);
assert.doesNotMatch(html, /pre\.phi==null\|\|pre\.phi===""/);
assert.match(sw, /"\.\/safety\.js"/);
assert.match(sw, /"\.\/farm-records\.js"/);
assert.match(sw, /"\.\/service-config\.js"/);
assert.match(sw, /"\.\/account\.js"/);
assert.match(sw, /v1\.8\.0-account-payment-preview/);

console.log("✓ index.html 所有程式區塊語法正確");
console.log("✓ 安全核心載入、版本與離線快取設定正確");
