const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const sw = fs.readFileSync(path.join(root, "sw.js"), "utf8");
const about = fs.readFileSync(path.join(root, "about.html"), "utf8");
const privacy = fs.readFileSync(path.join(root, "privacy.html"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.webmanifest"), "utf8"));

function pngSize(filename){
  const png=fs.readFileSync(path.join(root,filename));
  assert.equal(png.subarray(1,4).toString("ascii"),"PNG",filename+" 必須是 PNG");
  return {width:png.readUInt32BE(16),height:png.readUInt32BE(20)};
}

const inlineScripts = [];
const scriptRe = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
let match;
while ((match = scriptRe.exec(html))) inlineScripts.push(match[1]);
assert.ok(inlineScripts.length >= 2, "應找到主程式的 inline scripts");
inlineScripts.forEach((code, index) => new vm.Script(code, { filename: `index-inline-${index + 1}.js` }));

assert.ok(html.indexOf('<script src="./service-config.js"></script>') < html.indexOf("const DATA="), "service-config.js 必須在主程式前載入");
assert.ok(html.indexOf('<script src="./account.js"></script>') < html.indexOf("const DATA="), "account.js 必須在主程式前載入");
assert.ok(html.indexOf('<script src="./safety.js"></script>') < html.indexOf("const DATA="), "safety.js 必須在主程式前載入");
assert.ok(html.indexOf('<script src="./farm-records.js"></script>') < html.indexOf("const DATA="), "farm-records.js 必須在主程式前載入");
assert.match(html, /const APP_VERSION="0\.1\.9\.0"/);
assert.match(html, /<title>噴前查 SearchBefore/);
assert.match(html, /href="\.\/about\.html"/);
assert.match(html, /<link rel="canonical" href="https:\/\/searchbefore\.tw\/">/);
assert.match(html, /const PRIVACY_URL="https:\/\/searchbefore\.tw\/privacy\.html"/);
assert.match(html, /const SCHEMA_VERSION=3/);
assert.match(html, /PQC_SAFETY\.shouldShowVolumeApprox\(unit\)/);
assert.match(html, /PQC_SAFETY\.directCropLevels\(crop,DATA\)/);
assert.match(html, /id="rNotify" disabled/);
assert.match(html, /id="phiCustom" type="number" min="1" max="365"/);
assert.match(html, /function applyCustomPhi\(btn\)/);
assert.match(html, /PQC_SAFETY\.harvestStatus\(records,input\.plotId,input\.date\)/);
assert.match(html, /PQC_FARM\.buildTimeline\(list,farmList,p\.id\)/);
assert.match(html, /PQC_FARM\.exportCombinedCsv\(pesticideList,farmList/);
assert.doesNotMatch(html, /試用申請|授權碼啟用|方案與付款|付款功能尚未開放/);
assert.match(html, /id="homeFeatures"/);
assert.match(html, /function focusHomeSearch\(\)/);
assert.match(html, /公開測試中/);
assert.match(html, /請用一次真實流程，再告訴我們哪裡卡住/);
assert.match(html, /現在所有功能均開放，不登入也能直接使用/);
assert.match(html, /function searchPlotCrops\(raw\)/);
assert.match(html, /function pickPlotCrop\(crop\)/);
assert.match(html, /function useCustomPlotCrop\(\)/);
assert.match(html, /data-crop="" data-custom="0" oninput="searchPlotCrops\(this\.value\)"/);
assert.match(html, /cropSource:linkedCrop\?"registered":"custom"/);
assert.doesNotMatch(html, /一條完整工作流程|從噴藥前，一路接到採收後|最近更新|產品正在持續變好/);
assert.match(html, /合法用藥查詢/);
assert.match(html, /安全採收連動/);
assert.match(html, /id="accountInner" aria-live="polite"/);
assert.match(html, /id="homeAccountInner" aria-live="polite"/);
assert.match(html, /id="entryAccountInner" aria-live="polite"/);
assert.match(html, /選擇 Google 帳號/);
assert.match(html, /以訪客身分使用/);
assert.match(html, /登入或直接開始使用/);
assert.match(html, /兩種方式都能使用查詢、計算與田間紀錄/);
assert.match(html, /\.entry-hero h1\{[^}]*font-size:40px/);
assert.match(html, /function completeEntryWithGoogle\(\)/);
assert.match(html, /function openEntryGate\(\)/);
assert.match(html, /openEntryGate\(\);/);
assert.doesNotMatch(html, /store\.get\("onboarded"\)|store\.set\("onboarded"/);
assert.match(html, /window\.addEventListener\("load",function\(\)\{/);
assert.match(html, /d\.id="loadFailureBanner"/);
assert.match(html, /if\(loadFailureBanner\)loadFailureBanner\.remove\(\)/);
assert.doesNotMatch(html, /\},2500\);/);
assert.match(html, /id="recordHubHome"/);
assert.match(html, /田區新增／田區管理/);
assert.match(html, /其他田區紀錄/);
assert.match(html, /用藥歷史／匯出用藥紀錄/);
assert.match(html, /function openRecordHub\(section\)/);
assert.match(html, /function showRecordHub\(\)/);
assert.match(html, /id="navSearch" onclick="go\('search',this\)"/);
assert.match(html, /function openHomeOnLaunch\(\)\{\s*go\("search",document\.getElementById\("navSearch"\)\);\s*\}/);
assert.match(html, /renderPlotRecordBox\(\);openHomeOnLaunch\(\);/);
assert.match(html, /id="supportLink"[^>]*rel="noopener noreferrer"/);
assert.match(html, /id="supportCard" style="display:none/);
assert.match(html, /是否贊助都不影響任何功能或服務/);
assert.match(html, /贊助不會解鎖任何內容，也不影響功能或服務/);
assert.match(html, /function publicConfigHttpsUrl\(key\)/);
assert.doesNotMatch(html, /your-email@example\.com/);
assert.doesNotMatch(html, /贊助連結準備中/);
assert.match(html, /function canAddPlot\(\)\{\s*return true;/);
assert.doesNotMatch(html, /class="lock lockmark"/);
assert.match(html, /parsed\.protocol==="https:"/);
assert.doesNotMatch(html, /id="shopLinkInner"/);
assert.doesNotMatch(html, /function (?:renderShopLink|saveShopLink|disconnectShop)\(/);
assert.doesNotMatch(html, /linkedShop:store\.get\("linkedShop"\)/);
assert.doesNotMatch(html, /pre\.phi==null\|\|pre\.phi===""/);
assert.match(sw, /"\.\/safety\.js"/);
assert.match(sw, /"\.\/farm-records\.js"/);
assert.match(sw, /"\.\/service-config\.js"/);
assert.match(sw, /"\.\/account\.js"/);
assert.match(sw, /"\.\/about\.html"/);
assert.match(sw, /"\.\/brand-lockup\.png"/);
assert.match(sw, /"\.\/brand-logo-120\.png"/);
assert.match(html, /class="record-hub-back-icon" aria-hidden="true">←<\/span>/);
assert.match(html, /\.record-hub-back-icon\{[^}]*font-size:27px/);
assert.match(sw, /v0\.1\.9\.0-brand-verification/);
assert.match(about, /<h1>噴前查<span>SearchBefore<\/span><\/h1>/);
assert.match(about, /src="\.\/brand-lockup\.png"/);
assert.match(about, /Google 登入與資料使用/);
assert.match(about, /只取得 Google 提供的基本帳號識別資料/);
assert.match(about, /不會因 Google 登入而自動上傳至 Google 或 Firebase 資料庫/);
assert.match(about, /href="\.\/privacy\.html"/);
assert.match(privacy, /噴前查 SearchBefore 隱私權政策/);
assert.match(manifest.name, /^噴前查 SearchBefore/);
assert.deepEqual(pngSize("brand-logo-120.png"),{width:120,height:120});
assert.deepEqual(pngSize("icon-192.png"),{width:192,height:192});
assert.deepEqual(pngSize("icon-512.png"),{width:512,height:512});

console.log("✓ index.html 所有程式區塊語法正確");
console.log("✓ 安全核心載入、版本與離線快取設定正確");
