apply plugin: "com.android.application"

android {
    namespace "tw.searchbefore.ocrprototype"
    compileSdk 34

    defaultConfig {
        applicationId "tw.searchbefore.ocrprototype"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "0.1.0"
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation project(":ocr-feature")
}
